polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.wikiIndexView.as_view(), name='wikiIndex'),
    # url(r'^wiki/$', views.wikiIndexView.as_view(), name = 'wikiIndex'),
    # ex: /polls/5 (the number is the id of the question)
    #url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/vote/
    #url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # wikiPage
    url(r'^wiki/(?P<pk>[0-9]+)/wikiPage/$', views.WikiFormView.as_view(), name='wikiPage'),

    url(r'^wiki/editPage/$', views.editWikiPage, name='editWikiPage'),
    url(r'^wiki/(?P<pk>[0-9]+)/createPage/$', views.CreatePageView.as_view(), name='createWikiPage'),
    url(r'^wiki/createWiki/$', views.CreateWikiView.as_view(), name='createWiki'),

    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    url(r'^(?P<wiki_id>[0-9]+)/selectWiki/$', views.selectWiki, name='selectWiki'),
    # wikiDetial
    url(r'^(?P<pk>[0-9]+)/wikiDetail/$', views.WikiDetailView.as_view(), name='wikiDetail'),

]

webApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/models.py
from django.db import models
from django.urls import reverse

import datetime
from django.utils import timezone

# Create your models here.
from django.db import models


class Question(models.Model):

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

class Choice(models.Model):
    def __str__(self):
        return self.choice_text

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


class Wiki(models.Model):
    def __str__(self):
        return self.wiki_name

    def wiki_Page_List(self):
        print("wiki page list method")
        print(self.wikiPage_set())
        return self.wikiPage_set()

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('people.views.details', args=[str(self.id)])

    wiki_name = models.CharField(max_length=200, unique=True)
    wiki_purpose = models.TextField(default='')



class wikiPage(models.Model):
    def __str__(self):
        return self.page_name

    def get_absolute_url(self):
        return reverse('wikiPage', kwargs={'pk': self.pk})

    def wiki_list(self):
        return self.page_name

    wiki = models.ForeignKey(Wiki, on_delete=models.CASCADE, default=1)
    page_name = models.CharField(max_length=255, unique=True)
    page_text = models.TextField()


class ToDo(models.Model):
    # TODO create todo list model
    todo_name = models.CharField(max_length=200, unique=True)

polls/forms.py
from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .models import *


class EditPage(forms.ModelForm):
    class Meta:
        model = wikiPage
        fields = ['id', 'page_name', 'page_text', 'wiki']  # list of fields you want from model

    page_name = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    # page_name = forms.CharField(label= 'Page Name')
    # page_text = forms.CharField(widget=forms.Textarea)
    # wiki = forms.ChoiceField(label= "Wiki")

    # def getId(self):
    #    return self.fields['id']

    '''
    def clean_page_text(self):
        print('saving....')
        print(self.cleaned_data['page_text'])
        return self.cleaned_data['page_text']

    def clean_save(self):
        print('saving...')
        return HttpResponseRedirect(render('Saved'))
    '''


class WikiEdit(forms.ModelForm):
    class Meta:
        model = Wiki
        fields = ['wiki_name', 'wiki_purpose']

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import FormView
from .forms import *
from .models import Question, Choice, wikiPage, Wiki
from django.template import RequestContext


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'

    context_object_name = 'latest_question_list'


    def get_queryset(self):
        '''
        :return: the last five published questions
        '''
        print(Question.objects.all())
        return Question.objects.order_by('-pub_date')[:5]


class wikiIndexView(generic.ListView):
    template_name = 'polls/wikiIndex.html'
    context_object_name = 'wiki_List'

    def get_queryset(self):
        set = Wiki.objects.all()
        for w in set:
            print(w.id)
        return set


class WikiPagesView(generic.ListView):
    # wiki = Wiki.objects.get(pk)

    template_name = 'polls/WikiPages.html'

    # def get_queryset(self):
    # set =


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        print(selected_choice)
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html',
                      {
                          'question': question,
                          'error_message': "You didn't select a choice.",
                      })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class WikiDetailView(generic.ListView):
    model = wikiPage
    context_object_name = 'wiki_pageList'
    template_name = 'polls/wikiDetail.html'

    def get_queryset(self):
        set = wikiPage.objects.all()
        print(set)
        return set



def selectWiki(request, wiki_id):
    print(wiki_id)
    wiki = get_object_or_404(Wiki, pk=wiki_id)

    print(wiki.wiki_name)

    print('wiki: ' + str(wiki.wikipage_set.all))

    try:
        print('trying wiki')
        print(str(wiki.wikipage_set.get(pk=request.POST['wikiP'])))
        selected_wiki = wiki.wikipage_set.get(pk=request.POST['page'])
        print(selected_wiki.id)
    except (KeyError, wiki.DoesNotExist):
        print('wiki doesnt exist!')
        return render(request, 'polls/wikiDetail.html',
                      {
                          'wiki': wiki,
                          'error_message': "You didn't select a choice.",
                      })
    else:
        return HttpResponseRedirect(reverse('redirected!'))
        # return HttpResponseRedirect(reverse('polls:results', args=(wiki.id,)))


class CreatePageView(generic.edit.CreateView):
    model = wikiPage
    template_name = 'polls/wikiPageDetail.html'
    form_class = EditPage

    def form_valid(self, form):
        print('valid form')

        wikiField = form.cleaned_data['wiki']
        wiki = Wiki.objects.get(wiki_name=wikiField)  # get the associated wiki object
        print('Form Wiki Id: ' + str(wiki.id))
        form.save()

        return redirect('polls:selectWiki', wiki.id)


class CreateWikiView(generic.edit.CreateView):
    model = Wiki
    template_name = 'polls/wikiPageDetail.html'
    form_class = WikiEdit

    def form_valid(self, form):
        print('valid form')
        form.save()

        wikiField = form.cleaned_data['wiki_name']
        wiki = Wiki.objects.get(wiki_name=wikiField)  # get the associated wiki object

        print('Form Wiki Id: ' + str(wiki.id))

        return redirect('polls:selectWiki', wiki.id)



class WikiFormView(generic.edit.UpdateView):
    print("formview -- " + str(wikiPage.id))

    model = wikiPage

    # page = get_object_or_404(wikiPage.id)

    print(type(EditPage))

    form_class = EditPage

    # success_url = "polls:wikiIndex"
    # fields = ['page_name', 'page_text', 'wiki']

    template_name = 'polls/wikiPageDetail.html'

    def form_valid(self, form):
        print('valid form')

        wikiField = form.cleaned_data['wiki']
        wiki = Wiki.objects.get(wiki_name=wikiField)  # get the associated wiki object
        print('Form Wiki Id: ' + str(wiki.id))
        form.save()

        return redirect('polls:selectWiki', wiki.id)


def editWikiPage(request):
    context = RequestContext(request)

    print(request)
    print(request.POST['page_name'])

    # print(page.page_name + '--- editing')

    if request.method == 'POST':
        # create a form instance
        # form = editPage(page)
        page = wikiPage.objects.get(page_name=request.POST['page_name'])
        print(str(page) + '---got page')
        print(page.page_text)

        form = EditPage(page)

        if form.is_valid():
            # page = wikiPage.objects.get(page_name = form.cleaned_data['page_name'])
            print(str(page) + "---form is valid")
            page_id = form.cleaned_data['page_id']
            print(page_id)
            print(form.cleaned_data['wiki'])
            print('saving///')
            form.save(commit=True)
            print('Saved')
            return HttpResponseRedirect(reverse('polls:wikiIndex'))



        else:  # create blank form
            print(form.errors)
    else:
        form = EditPage()

    return HttpResponseRedirect(reverse('polls:wikiIndex'))


'''class wikiDetailView(generic.ListView):
    model = wikiPage
    context_object_name = 'wiki_List'
    template_name = 'polls/wikipage_detail.html'
'''
# TODO add a page to view all of the wiki pages in a wiki (use it's index) (ListView)

polls/templates/polls/candelete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Hi!
</body>
</html>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
    {% endfor %}
    <input type="submit" value="Vote"/>
</form>

<a href="{% url 'polls:index' %}"> All Questions </a>

polls/templates/polls/index.html
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li>
        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }} </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li> {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}"> Vote Again? </a></br>
<a href="{% url 'polls:index' %}"> All Questions </a>

polls/templates/polls/wikiDetail.html
<h1>{{wiki.wiki_name}} Detail Page - WikiDetail view </h1>


<h2> Wiki Purpose: </h2>
<p>
    <textarea readonly=True>{{ wiki.wiki_purpose }}</textarea>
</p>



<form action="{% url 'polls:selectWiki' wiki.id %}" method="post">
    {% csrf_token %}
    {% for page in wiki.wikipage_set.all %}
    <li>
        <a href="{% url 'polls:wikiPage' page.id %}"> {{page.page_name}} </a>
    </li>
    {% endfor %}
</form>

{% for page in wiki.wikipage.set.all%}
<li>
    <a href="{% url 'polls:selectWiki' page.id %}">{{ page.page_name }} </a>
</li>
{% endfor %}

<p>
    Links:
<li>
    <a href="{% url 'polls:wikiIndex' %}"> All Wikis </a>
</li>
<li>
    <a href="{% url 'polls:createWikiPage' wiki.id %}">Create New Page</a>
</li>

</p>

polls/templates/polls/wikiIndex.html
{% if wiki_List%}

<ul>
    {% for wiki in wiki_List %}
    <li>
        <a href="{% url 'polls:selectWiki' wiki.id %}">{{ wiki.wiki_name }} </a>
    </li>
    {% endfor %}
</ul>


{% elif wiki_pageList %}
<p>Index for wiki pages! Context is wiki_pagelist</p>
{% for wikipage in wiki_pageList %}
<li>
    <a href="{% url 'polls:wikiDetail' wikipage.id %}"> {{ wikipage.page_name }} - Detail for loop </a>
</li>
{% endfor %}


{% else %}
<p>No Index available</p>


{% endif %}

<li>
    <a href="{% url 'polls:wikiIndex' %}"> All Wikis </a>
</li>

<li><a href="{% url 'polls:createWiki' %}">Create New Wiki</a></li>

polls/templates/polls/wikiPageDetail.html
<!DOCTYPE html>
<html>
<body>
<h1>
    Editing -- {{ form.page_name.value }}
</h1>


<form method="post" action=" ">

    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
    <p>
        {{ field.errors }}
        {{ field.help_text }}
        {% if field == 'page_name' %}
        {{ field.text }}
        {% else %}
        {{ field }}
        {% endif %}
    </p>
    {% endfor %}

    <input type="submit" name="submit" value="Save Edits"/>
</form>
</body>

</html>

polls/templates/polls/wikiPageIndex.html
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li>
        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }} </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

polls/templates/polls/wikipage_detail.html
<h1>{{ wikiPage.page_name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form method="post">
    {% csrf_token %}
    {% for page in wikiPage.all %}
    <input type="radio" name="page" id="page{{ forloop.counter }}" value="{{ page.id }}"/>
    <label for="page{{ forloop.counter }}">{{ page.page_name }}</label><br/>
    {% endfor %}
    <input type="submit" value="Vote"/>
</form>

<a href="{% url 'polls:index' %}"> All Questions </a>